services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: app
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: ${NODE_ENV}
    ports:
      - "9000:9000"
    networks:
      - my_network
    volumes:
      # Mount the source code
      - .:/app
      # Don't mount node_modules from host
      - /app/node_modules
      # Don't mount dist from host
      - /app/dist
    env_file:
      - .env.development

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network

volumes:
  pgdata:

networks:
  my_network:
    driver: bridge
